#!/bin/bash

wget https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
tar xvf Python-3.7.1.tgz
cd Python-3.7.1
./configure --enable-optimizations --with-ensurepip=install
make -j4
sudo make altinstall
