#!/usr/bin/env python3.7

import sys
import rds

if len(sys.argv) != 2:
    print("Usage: showdb <spark|custom>")
    sys.exit(1)

rds.initialise_instance("group8.cqnxkff6jrcr.eu-west-1.rds.amazonaws.com", 3306, "kc506_rc691_CloudComputingCoursework", "foo", "hkXxep0A4^JZ1!H", sys.argv[1])
