#! /bin/bash
set -ex

function _init() {
    MAIN_FILE=wordlettercount.py
    mapfile -t AWS_CREDS < <(awk '/ = / {print $NF}' ~/.aws/credentials)
    if [ ! -f rds.py ]; then
        ln -s ../rds.py .
    fi
    ./resetdb
}

function _build() {
    # Get directory containing the script
    builddir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
    builddir="$(dirname "$builddir")" # One level up to project root
    docker build "$builddir" -f "$builddir/wordlettercount/Dockerfile" -t wordlettercount
    docker tag wordlettercount:latest clgroup8/wordlettercount
    docker push clgroup8/wordlettercount
}

function _kube_clean() {
    kubectl delete po --all
}

function _kube() {
    _init
    _kube_clean
    _build
    KUBE_MASTER=$(kubectl cluster-info | grep "master" | grep -o 'https://[^"]*.com')
    NUM_NODES="$(kubectl get nodes | grep -c node)"

    # Jars not needed on master because docker file puts them in imported folder (I think...)
    spark-submit \
        --master "k8s://$KUBE_MASTER" \
        --deploy-mode cluster \
        --name simpleapp \
        --conf spark.executor.instances="$((NUM_NODES - 1))" \
        --conf spark.kubernetes.pyspark.pythonVersion=3 \
        --conf spark.kubernetes.container.image=docker.io/clgroup8/wordlettercount:latest \
        --conf spark.kubernetes.container.image.pullPolicy=Always \
        "file:///usr/spark-2.4.0/work-dir/$MAIN_FILE" \
        "${AWS_CREDS[@]}" \
        "group8.cqnxkff6jrcr.eu-west-1.rds.amazonaws.com" \
        "3306" \
        "foo" \
        "hkXxep0A4^JZ1!H" \
        "kc506_rc691_CloudComputingCoursework" \
        "s3a://kubernetes.group8.samples/sample-$1.txt"
    ./showdb
}

function _local() {
    _init
    spark-submit \
        --jars aws-java-sdk-1.7.4.jar,hadoop-aws-2.7.0.jar \
        "$MAIN_FILE" \
        "${AWS_CREDS[@]}" \
        "group8.cqnxkff6jrcr.eu-west-1.rds.amazonaws.com" \
        "3306" \
        "foo" \
        "1234567890" \
        "kc506_rc691_CloudComputingCoursework" \
        "s3a://kubernetes.group8.samples/sample-$1.txt"
    ./showdb
}

case $1 in
    kubernetes|k8s)
        shift
        _kube "$@"
        ;;
    local|l)
        shift
        _local "$@"
        ;;
    build|b)
        _build
        ;;
    *)
        echo "Usage: spark [kubernetes|local|build] INPUT-SAMPLE-ID"
        echo "kubernetes - Launch in kubernetes"
        echo "local - Launch locally"
        exit 1
esac
