#!/usr/bin/env python3.7

import sys
from utils import db

if len(sys.argv) != 2:
    print("Usage: showdb <spark|custom>")
    sys.exit(1)

db.print_db_contents(
    "group8-eu-west-1.cqnxkff6jrcr.eu-west-1.rds.amazonaws.com",
    3306,
    "kc506_rc691_CloudComputingCoursework",
    "foo",
    "hkXxep0A4^JZ1!H",
    sys.argv[1],
)
